apiVersion: v1
kind: Service
metadata:
    namespace: snowpackage-site
    name: snowpackage-site
    labels:
        app: snowpackage-site
spec:
    ports:
    - port: 3010
      protocol: TCP
      targetPort: 3010
    selector:
        app: snowpackage-site
    type: ClusterIP