kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snowpackage-site-pvc
  namespace: snowpackage-site
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: snowpackage-site-hostpath