apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: morfeu-workflow-    # name of the workflow spec
  namespace: argo
spec:
  entrypoint: morfeu-ci
  volumes:
  - name: workdir
    emptyDir: {}
  arguments:
    parameters:
    - name: repo
      value: https://github.com/danigiri/morfeu.git
    - name: revision
      value: master
  templates:
  - name: morfeu-ci
    steps:
    - - name: checkout
        template: checkout
  - name: checkout
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
    outputs:
      artifacts:
      - name: source
        path: /mnt/vol
    container:
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args: ["cd /src && git status && ls -l"]
      volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
