apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: morfeu-workflow-            # name of the workflow spec
  namespace: argo
spec:
  schedule: "*/2 18-23,1-2 * * *"
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: morfeu-ci
    parallelism: 1                            # only one instance of the workflow at the time
    volumes:
    - name: workdir
      emptyDir: {}
    volumeClaimTemplates:
      - metadata:
          name: source
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Mi
    onExit: save-code
    arguments:
      parameters:
      - name: registry
        value: registry.container-registry.svc.cluster.local:5000
      - name: repo							# no protocol in front!
        value: github.com/danigiri/morfeu.git
      - name: revision
        value: master
      - name: versionURL
        value: morfeu-service.morfeu.svc.cluster.local:8980/metadata/version.txt
    templates:
    - name: morfeu-ci
      steps:
      - - name: checkout
          template: checkout
      - - name: build
          template: build
          when: "'{{steps.checkout.outputs.result}}' == 'go'"
          arguments:
            artifacts:
              - name: source
                from: "{{steps.checkout.outputs.artifacts.source}}"
    - name: checkout
      inputs:
        artifacts:
        - name: getsource
          path: /src
          git:
            repo: "https://{{workflow.parameters.repo}}"
            revision: "{{workflow.parameters.revision}}"
      outputs:
        artifacts:
        - name: source
          path: /mnt/vol
      container:
        image: frolvlad/alpine-bash
        command: ["/bin/bash", "-c"] # we curl the version from the live pod, compare it with the pom.xml contents
        args: ["cd /src && apk -q add git curl && if [[ '<version>'$(curl -s '{{workflow.parameters.versionURL}}')'</version>' != $(grep '<version>' pom.xml|head -1|tr -d '[:space:]') ]]; then mv /src/* /mnt/vol/ && echo go; else echo stop; fi"]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
    - name: build
      inputs:
        artifacts:
          - name: source
            path: /src
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - '--dockerfile=Dockerfile'
          - '--context=dir:///src'
          - '--destination={{workflow.parameters.registry}}/morfeu'
          - '--insecure'
          - '--cache=true'
          - '--verbosity=info'

    - name: save-code
      container:
        image: alpine:3
        command:
          - "true"
        volumeMounts:
          - name: source
            mountPath: /source
      outputs:
        artifacts:
          - name: morfeu-source
            path: /source/morfeu-source
            s3:
              key: morfeu-source
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
    
#        image: frolvlad/alpine-bash
#        command: ["/bin/bash", "-c"]
#        args: ["cd /src && pwd && ls -l && cd / && pwd && ls -l && cd /mnt && pwd && ls -l"]


