kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage:  5Gi