kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-cache-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage:  1Gi