kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snow-package-pvc
  namespace: snow-package
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi