apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: morfeu
    name: snow-package
    labels:
        app: snow-package
        app.kubernetes.io/name: snow-package
        app.kubernetes.io/component: middleware
        app.kubernetes.io/part-of: morfeu
        app.kubernetes.io/managed-by: argocd
spec:
    replicas: 1
    selector:
        matchLabels:
            app: snow-package
    template:
        metadata:
            labels:
                app: snow-package
                app.kubernetes.io/name: snow-package
                app.kubernetes.io/component: middleware
                app.kubernetes.io/part-of: morfeu
                app.kubernetes.io/managed-by: argocd
        spec:
            containers:
            - image: localhost:32000/snow-package:latest
              name: snow-package
              imagePullPolicy: Always
              args: [" -D__RESOURCES_PREFIX=file:///var/lib/jetty/"]